kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-dep
  namespace: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: nitinpanwar6963/expense
        ports:
        - containerPort: 5000

        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_DB
          value: "expense_db"
        - name: MYSQL_PORT
          value: "3306"
