kind: Deployment
apiVersion: apps/v1
metadata:
  name: expense-dep
  namespace: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql

  template:
      metadata:
        name: expense
        labels:
          app: mysql
      spec:
        containers:
        - name: mysql
          image: mysql:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: MYSQL_DATABASE
            value: "expense_db"
